name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.arch.os }}

    strategy:
      matrix:
        rust-version: ['1.65', 'stable']
        arch:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest, suffix: '' }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-latest, suffix: '' }
          - { target: x86_64-pc-windows-msvc, os: windows-latest, suffix: '.exe' }
          - { target: x86_64-apple-darwin, os: macos-latest, suffix: '' }

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          profile: minimal
          override: true

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libopus-dev

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --locked --target ${{ matrix.arch.target }}

      - name: Build Release Binary
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --locked --target ${{ matrix.arch.target }}