# https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
name: Deploy on Fly

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release tag
        id: release-tag
        run: |
          echo "TAG=$(curl -s ${{ github.api_url }}/repos/${{ github.repository }}/releases/latest | jq '.tag_name' | sed 's/\"//g')" >> $GITHUB_OUTPUT

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release-tag.outputs.TAG }}

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy on Fly
        run: flyctl deploy --remote-only
        env:
          # https://fly.io/docs/reference/deploy-tokens/
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}