# https://codingpackets.com/blog/rust-binary-and-docker-releases-using-github-actions/#release-workflow
name: Tag

permissions:
  contents: "write"

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  tag:
    if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release') }}
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          # https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
          ssh-key: ${{ secrets.COMMIT_KEY }}

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Get version from Cargo.toml
        id: get-version
        run: echo "VERSION=v$(cargo pkgid | cut -d# -f2)" >> $GITHUB_OUTPUT
        working-directory: ./bot

      - name: Push tag
        shell: "bash"
        run: git tag ${{ steps.get-version.outputs.VERSION }} && git push --tags
